### ISSUE TITLE
error: ‘SSL_R_SHORT_READ’ was not declared in this scope

### ISSUE THREAD

**Issue by lbpierre** [JusticeRage/Manalyze#18]
System info:
`uname -svrom: Linux 4.9.0-1-amd64 #1 SMP Debian 4.9.6-3 (2017-01-28) x86_64 GNU/Linux
lsb_release -c: stretch
`
When invoking command: `make` 
The following error appear: 
`/home/pierre/Manalyze/plugins/plugin_virustotal/plugin_virustotal.cpp: In function ‘bool plugin::vt_api_interact(const string&, const string&, std::__cxx11::string&, plugin::sslsocket&)’:
/home/pierre/Manalyze/plugins/plugin_virustotal/plugin_virustotal.cpp:276:84: error: ‘SSL_R_SHORT_READ’ was not declared in this scope
  if (error != boost::asio::error::eof && error.value() != ERR_PACK(ERR_LIB_SSL, 0, SSL_R_SHORT_READ)) {
                                                                                    ^
CMakeFiles/plugin_virustotal.dir/build.make:62 : la recette pour la cible « CMakeFiles/plugin_virustotal.dir/plugins/plugin_virustotal/plugin_
virustotal.cpp.o » a échouée
`

**Comment by JusticeRage** [comment]
From what I understand, this is a problem linked to boost < 1.62 not supporting openssl 1.1.
Can you please confirm that this is the source of the problem by pasting the output of `openssl version`?

Thanks!

**Comment by lbpierre** [comment]
`OpenSSL 1.1.0d  26 Jan 2017 (Library: OpenSSL 1.1.0e  16 Feb 2017)`
