### ISSUE TITLE
Does it support Mac os?

### ISSUE THREAD

**Issue by kevien** [JusticeRage/Manalyze#23]
Does it support Mac os?

**Comment by JusticeRage** [comment]
I have no idea as I don't own any Apple device. Please try building it and let me know what happens.

**Comment by lctrcl** [comment]
@kevien I've built docker image for myself, and using it on a mac
https://hub.docker.com/r/evanowe/manalyze/
Feel free to use it or build yourself (instructions in the image).

**Comment by kevien** [comment]
thanks
