### ISSUE TITLE
when i run on  win7,it error accured.

### ISSUE THREAD

**Issue by kevien** [JusticeRage/Manalyze#24]
error info:
C:\Users\xxx\Desktop\manalyze>manalyze.exe --plugins=peid,clamav --dump all Churrasco.exe
[!] Error: [Yara compiler] yara_rules/clamav.yara(845778) : internal fatal error

i am confused how to use it on win7 and how yara integrate it ？  thanks

**Comment by kevien** [comment]
full main  error msg；
[!] Error: [Yara compiler] yara_rules/clamav.yara(845778) : internal fatal error
[!] Error: [Yara compiler] yara_rules/clamav.yara(845788) : internal fatal error
[!] Error: [Yara compiler] yara_rules/clamav.yara(845798) : internal fatal error
[!] Error: [Yara compiler] yara_rules/clamav.yara(845808) : internal fatal error
[!] Error: [Yara compiler] yara_rules/clamav.yara(912598) : internal fatal error
[!] Error: [Yara compiler] yara_rules/clamav.yara(912618) : internal fatal error
[!] Error: [Yara compiler] yara_rules/clamav.yara(921658) : internal fatal error
[!] Error: [Yara compiler] yara_rules/clamav.yara(930908) : internal fatal error
[!] Error: Could not compile yara rules (8 error(s)).
[!] Error: ClamAV rules haven't been generated yet!
[!] Error: Please run yara_rules/update_clamav_signatures.py to create them, and refer to the documentation for additional information.
[*] Warning: Yara callback received an unhandled message (5).
* Manalyze 0.9 *

-------------------------------------------------------------------------------

**Comment by JusticeRage** [comment]
Thanks for the report. It seems that the ClamAV rules cannot be compiled currently. 
I will update the Python script asap, but it seems that your problems might be a bit different.

Let me first update the issue referenced in #21 and check again on this one.
