### ISSUE TITLE
Nullptr dereference in Resource::extract()

### ISSUE THREAD

**Issue by rc0r** [JusticeRage/Manalyze#25]
Hi,

in case `Resource::extract()` is called with an invalid `destination` argument the calling process segfaults because `fwrite()` tries to write to a `FILE *` object which in fact is NULL.

I'd consider this a minor bug, since one could argue using the API in a wrong way is the user's fault. However in that case you may want to avoid the segmentation fault and guide your users by providing an appropriate error message.

So a patch could look sth. like the following (**disclaimer: untested!**):

```c
FILE* out = fopen(destination.string().c_str(), "a+");

+ if(out == nullptr) {
+     PRINT_ERROR << "Opening file " << destination.string().c_str() << " failed!" << std::endl;
+     return false;
+ }

```

Cheers
rc0r

**Comment by JusticeRage** [comment]
Thanks for pointing this out and providing a fix! I agree that the API should do minimal checks to prevent users from shooting themselves in the foot.
