### ISSUE TITLE
Infinite loop when parsing resources

### ISSUE THREAD

**Issue by bennw** [JusticeRage/Manalyze#31]
[manalyze_infloop.zip](https://github.com/JusticeRage/Manalyze/files/1927021/manalyze_infloop.zip)

**CAUTION: malware attached**

The file in the attached zip gives an infinite loop when parsing resources, spamming the following error messages:
```
[*] Warning: The PE contains duplicate resources. It was almost certainly crafted manually.
[*] Warning: Could not locate the section containing resource 65280. Trying to use the RVA as an offset...
[*] Warning: Resource 65280 has a size of 0!
```

Seems to be related to size 0 resources.

**Comment by JusticeRage** [comment]
Hi! Thanks a lot for the report! I'm a little busy at the moment but I'll look into this file ASAP!

**Comment by JusticeRage** [comment]
I've started looking into this issue. I can confirm that the issue takes place during the parsing of the resources, but at the moment I cannot confirm that there is indeed an infinite loop taking place. It could be that parsing so many resources and printing out all there warnings takes a very long time. Either way, something needs to be done about it!

**Comment by JusticeRage** [comment]
Integer overflow on the number of resources? I'll be sure to keep that in mind.
On my end, I've launched the parser with all messages disabled hoping that I'll be able to reach the end of the analysis!

**Comment by JusticeRage** [comment]
Okay, the Manalyze has been running for weeks on your sample and still doesn't show any signs of stopping. I'm revising my initial judgement: you may have been right that the program somehow enters an infinite loop.
I'll keep investigating this issue!
