### ISSUE TITLE
Slowdowns on malformed PEs which have a high number of sections

### ISSUE THREAD

**Issue by JusticeRage** [JusticeRage/Manalyze#4]
It was reported that PE files with a very high number of sections cause the analysis to be extremely slow.
The issue has been traced down to ``Section::get_raw_data()`` which opens and closes the input file with every call. The file handle should be cached and sanity checks need to be put in place to prevent unnecessary operations.

The result of ``PE::get_filesize`` should also be cached instead of being computed with every call.

**Comment by JusticeRage** [comment]
@rewolf I've made the modifications you suggested, however I don't find that the speed improvement is stellar.
Do you consider that this issue is fixed, or should there be a configuration parameter such as ``pe.max_sections_allowed`` in ``manalyze.conf`` to reject PEs with too many sections?

**Comment by rwfpl** [comment]
I think you can close it now. Currently it spends most of the time on output printing. It's a lot better than it was anyway.
