### ISSUE TITLE
Clamav Cloudflare DDoS protection causes signature updater to fail.

### ISSUE THREAD

**Issue by shubb30** [JusticeRage/Manalyze#43]
Clamav has recently started using Cloudflare to front their signature download page.  If you use Python, then the response will be a 403.  The text says that it wants cookies to be enabled.  Using a web browser works fine to download the AV update package.

```
>>> import requests
>>> r = requests.get("http://database.clamav.net/daily.cvd")
>>> r
<Response [403]>
```

**Comment by JusticeRage** [comment]
Thanks for reporting this!
I'll look into workarounds shortly.
