### ISSUE TITLE
Analysis of certain sample does not end 

### ISSUE THREAD

**Issue by kohnakagawa** [JusticeRage/Manalyze#44]
Analysis of this sample
[8323af43ff507b82c87b38b45ea4c79fae4b49ed453590101373c18aae96b8fb](https://www.virustotal.com/gui/file/8323af43ff507b82c87b38b45ea4c79fae4b49ed453590101373c18aae96b8fb/details) does not end.

```
$ ./bin/manalyze --output=json 8323af43ff507b82c87b38b45ea4c79fae4b49ed453590101373c18aae96b8fb
```

I investigated a little bit, and I suspect that the parsing logic of resources contains some bugs.
I think that recursive parse of resources tree does not end properly.

**Comment by JusticeRage** [comment]
Thanks a lot for reporting this! I'll look into it shortly.

**Comment by kohnakagawa** [comment]
Hi.

I encountered a similar issue during scanning [this sample](https://www.virustotal.com/gui/file/4809eb53debf0923f50d3ba05c05b5b149f3d6f1c65d43871044522f80ea3241/details).

**Comment by JusticeRage** [comment]
Thanks! I am able to reproduce the issue and am currently investigating it.

**Comment by kohnakagawa** [comment]
Thank you for fixing this!

**Comment by JusticeRage** [comment]
No, thank you for reporting the issue!
