### ISSUE TITLE
Exporting JSON to a File

### ISSUE THREAD

**Issue by JasonKramer525** [JusticeRage/Manalyze#45]
Is there any way to save the JSON output to a file? I guess I could also parse through the console output, but it would be helpful to download it directly to a file.

**Comment by JusticeRage** [comment]
Jave you tried `manalyze -o json sample.exe > output.txt`?

**Comment by JasonKramer525** [comment]
> Jave you tried `manalyze -o json sample.exe > output.txt`?

Thanks, that worked! Also, what is the best way to run update_clamav_signatures.py in the docker container so that it stays updated every time?

**Comment by JusticeRage** [comment]
The docker container is not supported by me, and signature updates regularly need manual fixing anyway.
I'll leave it as an exercise to the reader to set up a cron job for the automation part.
