### ISSUE TITLE
Could not load yara rules

### ISSUE THREAD

**Issue by JessyGothik** [JusticeRage/Manalyze#55]
Hi!

I have a problem with the Yara rules. When I try to run an analysis (Example: manalyze sample.exe -p strings), I have the following error:

```
[!] Error: Could not load yara_rules/suspicious_strings.yara!
[!] Error: Could not load yara_rules/domains.yara!
* Manalyze 0.9 *
```

I checked the folder "/usr/local/manalyze/yara_rules" and there are Yara's rules.

Can you help me with this problem, please?

**Comment by JusticeRage** [comment]
Thanks for the report! Interesting, I'm assuming you checked out the code from GitHub and built it yourself? On which OS?
If you run the command from `/usr/local/manalyze`, does it work (although it should work from any directory, obviously)?

**Comment by egalitaire** [comment]
Hello. Hope all is well. I am having the same issue and I was curious if there was ever a resolution for it.

**BACKGROUND**

I am working with a preinstalled VM of Remnux.

Distributor ID: **Ubuntu**
Description: **Ubuntu 20.04.6 LTS**
Release: **20.04**
Codename: **focal**

**PREPARATORY STEPS**

I temporarily enabled network access to do the following:

- Remnux Upgrade (successfully completed)
- Remnux Update (successfully completed)
- sudo apt update (successfully completed)
- sudo apt autoremove (successfully completed)
- sudo apt --fix-broken install (successfully completed)

to ensure I am working with the most current version.

**ISSUE**

The original command I typed was as follows (the test file is pefile.exe)

     ~$ manalyze --plugins=strings,packer,resources pefile.exe
**Results**
\[!\] Error: Could not load yara_rules/suspicious_strings.yara!
\[!\] Error: Could not load yara_rules/domains.yara!

\* Manalyze 0.9 \*
\-------------------------------------------------------------------------------
/home/remnux/Working/pefile.exe
\-------------------------------------------------------------------------------

Summary:
\---------

Architecture: IMAGE_FILE_MACHINE_I386
Subsystem: IMAGE_SUBSYSTEM_WINDOWS_CUI
Compilation Date: 2012-Dec-20 19:14:11

\[ SUSPICIOUS \] The PE is possibly packed.
Section .text is both writable and executable.
Section .rdata is both writable and executable.
Section .data is both writable and executable.
Section .reloc is both writable and executable.

**TROUBLESHOOTING STEPS**

I followed your suggestion from above, and also ran it from the \_/usr/local_ folder as such:

     ~$ manalyze --plugins=strings,packer,resources /home/remnux/Working/pefile.exe

I received the same result.

So, I decided that perhaps one of the plugins was causing the issue and decided to only include a single plugin and step through them.

I started off with the **strings** plugin.

    ~$ manalyze --plugins=strings pefile.exe
**Results**
\[!\] Error: Could not load yara_rules/suspicious_strings.yara!
\[!\] Error: Could not load yara_rules/domains.yara!
\* Manalyze 0.9 \*
\-------------------------------------------------------------------------------
/home/remnux/Working/pefile.exe
\-------------------------------------------------------------------------------

Summary:
\---------
Architecture: IMAGE_FILE_MACHINE_I386
Subsystem: IMAGE_SUBSYSTEM_WINDOWS_CUI
Compilation Date: 2012-Dec-20 19:14:11
So…it happens with the **strings** plug-in, so I tried:

     ~$ manalyze --plugins=packer pefile.exe

\* Manalyze 0.9 \*

\-------------------------------------------------------------------------------
/home/remnux/Working/pefile.exe
\-------------------------------------------------------------------------------

Summary:
\---------

Architecture: IMAGE_FILE_MACHINE_I386
Subsystem: IMAGE_SUBSYSTEM_WINDOWS_CUI
Compilation Date: 2012-Dec-20 19:14:11

\[ SUSPICIOUS \] The PE is possibly packed.
Section .text is both writable and executable.
Section .rdata is both writable and executable.
Section .data is both writable and executable.
Section .reloc is both writable and executable.

No Yara error messages with the **packer** plugin, so I tried it with the **resources** plugin:

~$ manalyze --plugins=resources pefile.exe

\* Manalyze 0.9 \*
\-------------------------------------------------------------------------------
/home/remnux/Working/pefile.exe
\-------------------------------------------------------------------------------

Summary:
\---------
Architecture: IMAGE_FILE_MACHINE_I386
Subsystem: IMAGE_SUBSYSTEM_WINDOWS_CUI
Compilation Date: 2012-Dec-20 19:14:11

No issues here either. So I believe it is the **strings** plugin that is causing it. Any information on how to correct it would be greatly appreciated.

**Comment by JusticeRage** [comment]
Hi! Thanks for the report!
Basically, the issue here seems to be that Manalyze cannot file its yara rules, which are placed in a folder named `yara_rules` in its own directory. All plugins that don't rely on yara rules will still function normally.

Is Manalyze directly packaged with Remnux, or did you build it yourself?
You also showed the following command line:

```
 ~$ manalyze --plugins=strings,packer,resources /home/remnux/Working/pefile.exe
```

The `~` in the prompt leads me to think it was run from your `$HOME`. Would you also be able to tell me the output of `which manalyze` and see if running the program from that folder changes anything?

**Comment by egalitaire** [comment]
Ivan,

Thank you for the reply, I appreciate your quick response. Some responses to your questions.

Is Manalyze directly package with Renmux, or did you build it yourself.
The first few times I ran it and it came up with noted errors, it was the version directly packaged with Remnux. 
After reading one of the posts, I rebuilt it from the git source and still received the same errors after running it.
I erred when I posted that command with that particular prompt. It should have looked like these (note that I changed the “working” directory to all lowercase after sending the previous examples.
***@***.***:/usr/local/manalyze$ manalyze --plugins=strings,packer,resources /home/remnux/working/pefile.exe
I get the same two errors: [!] Error: Could not load yara_rules/suspicious_strings.yara! and [!] Error: Could not load yara_rules/domains.yara!
***@***.***:~/working$ manalyze --plugins=strings,packer,resources pefile.exe
I get the same outcome.
The remainder of the output from both commands is as follows:
* Manalyze 0.9 *

-------------------------------------------------------------------------------
/home/remnux/working/pefile.exe
-------------------------------------------------------------------------------

Summary:
--------
Architecture:     IMAGE_FILE_MACHINE_I386
Subsystem:        IMAGE_SUBSYSTEM_WINDOWS_CUI
Compilation Date: 2012-Dec-20 19:14:11

[ SUSPICIOUS ] The PE is possibly packed.
    Section .text is both writable and executable.
    Section .rdata is both writable and executable.
    Section .data is both writable and executable.
    Section .reloc is both writable and executable.
My next step is to remove and reinstall it completely to see if I can eliminate the issue.

**Comment by JusticeRage** [comment]
Thanks for the update. So, I'm guessing that the `/usr/local/` folder only contains the manalyze binary but not the yara rules... and most likely many plugins would be missing either. Just in case, can you verify that there is no `yara_rules` folder in there? It would also be helpful if you could find out where that folder is (maybe with `find / -type d -name yara_rules`.

To prevent this exact problem, Manalyze looks for its yara rules and plugins first in the same folder as the binary, then in `/etc/manalyze`: https://github.com/JusticeRage/Manalyze/blob/b6800ffcf2f7f4e82fe1f94d0eb2736e75e175ec/src/main.cpp#L554

It's possible Remnux's packaging doesn't respect this convention, in which case things are just not going to work.
Normally, if you built Manalyze from source, you shouldn't have any issues, _but_ if the Remnux version and the source version coexist on your system it's still possible the wrong one was invoked (even if you did `make install`, maybe the Remnux version is still found earlier in `$PATH`). Would you be able to go to the folder where you built Manalyze and run `./manalyze` (not just `manalyze`)?

**Comment by egalitaire** [comment]
Hello again,

I reverted the VM to right after installing it, and doing apt update/upgrade. I ran it against an EXE with the same command string and got the same result.

Here is a tree listing of the files in /usr/local/manalyze :

[-rwxr-xr-x root    ]  ./attack.py
[-rwxr-xr-x root    ]  ./libhash-library.so
[-rwxr-xr-x root    ]  ./libmanacommons.so
[-rwxr-xr-x root    ]  ./libmanape.so
[-rwxr-xr-x root    ]  ./libplugin_authenticode.so
[-rwxr-xr-x root    ]  ./libplugin_virustotal.so
[-rwxr-xr-x root    ]  ./libyara.so
[-rwxr-xr-x root    ]  ./manalyze
[-rw-r--r-- root    ]  ./manalyze.conf
[-rw-r--r-- root    ]  ./plot_timestamps.py
[drwxr-xr-x root    ]  ./yara_rules
[-rw-r--r-- root    ]  ./yara_rules/bitcoin.yara
[-rw-r--r-- root    ]  ./yara_rules/company_names.yara
[-rw-r--r-- root    ]  ./yara_rules/compilers.yara
[-rw-r--r-- root    ]  ./yara_rules/domains.yara
[-rw-r--r-- root    ]  ./yara_rules/findcrypt.yara
[-rw-r--r-- root    ]  ./yara_rules/magic.yara
[-rw-r--r-- root    ]  ./yara_rules/monero.yara
[-rwxr-xr-x root    ]  ./yara_rules/parse_clamav.py
[-rw-r--r-- root    ]  ./yara_rules/peid.yara
[-rw-r--r-- root    ]  ./yara_rules/suspicious_strings.yara
[-rw-r--r-- root    ]  ./yara_rules/third_party_code.yara
[-rwxr-xr-x root    ]  ./yara_rules/update_clamav_signatures.py

The files all seem to be in the correct locations and have the correct privileges.

running find / -type d -name yarn_rules yields:

/usr/local/manalyze/yara_rules

Here is the $PATH as it exists:

/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

So:

1. The yara_rules folder exists in the same folder as the binary /usr/local/manalyze/yara_rules
2. I also created a directory in /etc called manalyze and copied the yara_rules directory and files into it and tried rerunning it and got the same results.

In the words of the immortal Homer Simpson D’oh! I feel really stupid, but I ran it as sudo and it ran without an issue. I had been running the binary without it before. I think I need to get some food and some caffeine. Im finding that REMNux wants that for everything.

**Comment by JusticeRage** [comment]
Alright! Weird design choice, but at least we know what happened.

**Comment by egalitaire** [comment]
I suppose that’s the way it was setup in REMnux. Anyway, sorry to have troubled you.
