### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by 93ZhangGe** [JusticeRage/Manalyze#56]
Hi

I am writing to you regarding an issue I encountered while installing the Manalyze program. After installing the necessary dependencies, when I proceeded to execute the command "make -j5," I encountered the following error:

/home/rpadmin/Manalyze-master/plugins/plugin_virustotal/json_spirit/json_spirit_reader_template.h:446:114: error: ‘boost::placeholders’ has not been declared
Uint64_action new_uint64 ( boost::bind( &Semantic_actions_t::new_uint64, &self.actions_, boost::placeholders::_1 ) );

I believe this error is related to the use of 'boost::placeholders' in the code, which seems to be causing a declaration issue. In order to resolve this problem, I would greatly appreciate your guidance and assistance.

Could you please provide me with instructions on how to address this error? I would be grateful for any insights or suggestions you can offer. I am eager to successfully install and utilize the Manalyze program for my needs.

Thank you for your attention to this matter. I look forward to your prompt response.
OS: UbuntuServer 16.04

**Comment by JusticeRage** [comment]
Hi! Thanks for reporting this! Looks like this is an incompatibility caused by a change in Boost libraries. Let me check if there is a more recent version of JSON Spirit Reader and get back to you!
