### ISSUE TITLE
Import analyzer plugin rule suggestions vol. 2

### ISSUE THREAD

**Issue by henke37** [JusticeRage/Manalyze#9]
```LoadDriver``` Yet another LoadLibrary replacement
```LoadTypeLib``` Possible LoadLibrary replacement?
```waveInOpen|DirectSoundCaptureCreate``` Records audio
```EnableRouter|SetAdapterIpAddress|SetIpInterfaceEntry``` Messes with the network configuration
```OleGetClipboard ``` Reads the clipboard
```CertAddCertificateContextToStore|CertOpenSystemStore``` Manipulates the system certificate store
```InitiateShutdown|ExitWindows``` Turns the system off
```Wmi*``` Uses WMI
```SHTestTokenMembership|CheckTokenMembership|IsUserAnAdmin``` Checks for privileges
```SHEnumKeyEx``` Another way to access the registery

**Comment by JusticeRage** [comment]
Thanks for these! I'll add them very soon as well.

**Comment by JusticeRage** [comment]
- According to the MSDN, [LoadDriver](https://msdn.microsoft.com/en-us/library/aa911481.aspx) is only available in Windows Mobile. As such, I'm not sure it should be included.
- I have also tried to use `LoadTypeLib` to load a library such as `kernel32`, but was unable to do so - I'm assuming it can only be used to load `.tlb` libraries.
- To the best of my knowledge, the WMI isn't accessed with direct WMI* calls but through COM requests instead. Are there specific WMI functions that you know about? In any case, thinking about the WMI gave me the idea to add all the well known namespaces (i.e. `ROOT\CIMV2`) to the suspicious strings plugin, so thanks for that!

I'm pushing the commit adding the rest of the suggestions in a minute, let me know if you consider that this issue can be closed.

**Comment by henke37** [comment]
Yeah, that's fine with me.
